cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIARZ6TUUMLFQIAGB22
      secret-key: vMHCQKgo8ELlcM1xE6R26hHSGEPSBdBivZj+clEt
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/124461032214/ExampleQueueSQS
server:
  port: 8081